class TipoAFD:
    IDENTIFICADOR = 'IDENTIFICADOR'
    CADENA = 'CADENA'
    NUMEROS = 'NUMEROS'
    SIMBOLO_SIMPLE = 'SIMBOLO_SIMPLE'
    COMENTARIOS_Y_SLASH = 'COMENTARIOS_Y_SLASH'
    OPERADOR_RELACIONAL = 'OPERADOR_RELACIONAL'
    NINGUNO = 'NINGUNO'
StopIteration